title: Rows
label: Rows
order: 2
status: 'wip'
context:
  row:
    modifier: 'row'
    style: 'background-color: lightblue;'
variants:
  - name: Outer Row
    context:
      row:
        modifier: 'row--outer'
